In [15]:
india_symbols = ['^INDIAVIX','^NSEI','^CNXIT']
start = datetime.datetime(2018, 1, 1)
end = datetime.datetime(2024, 3, 6)

# Function to fetch historical data for a symbol
def fetch_data(symbol):
    data = yf.download(symbol, start=start, end=end)
    return data[['Open','High','Low' ,'Close', 'Volume']].rename(columns={'Open': f'{symbol}_open','Low': f'{symbol}_low','High': f'{symbol}_high','Close': f'{symbol}_close', 'Volume': f'{symbol}_volume'})

# Fetch data for all symbols and create a DataFrame
dfs = [fetch_data(symbol) for symbol in india_symbols]
result_df = pd.concat(dfs, axis=1, join='inner')

# Print the resulting DataFrame
print(result_df.head())

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['^INDIAVIX']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

Empty DataFrame
Columns: [^INDIAVIX_open, ^INDIAVIX_high, ^INDIAVIX_low, ^INDIAVIX_close, ^INDIAVIX_volume, ^NSEI_open, ^NSEI_high, ^NSEI_low, ^NSEI_close, ^NSEI_volume, ^CNXIT_open, ^CNXIT_high, ^CNXIT_low, ^CNXIT_close, ^CNXIT_volume]
Index: []

In [17]:
fetch_data('^CNXIT - NIFTY IT.')

[*********************100%%**********************]  4 of 4 completed

3 Failed downloads:
['NIFTY', '-', 'IT.']: Exception('%ticker%: No timezone found, symbol may be delisted')

Price      ^CNXIT - NIFTY IT._open                          \
Ticker                           - IT. NIFTY        ^CNXIT
Date
2018-01-02                     NaN NaN   NaN  11587.849609
2018-01-03                     NaN NaN   NaN  11617.349609
2018-01-04                     NaN NaN   NaN  11599.049805
2018-01-05                     NaN NaN   NaN  11575.450195
2018-01-08                     NaN NaN   NaN  11674.349609
...                            ...  ..   ...           ...
2024-02-28                     NaN NaN   NaN  37926.648438
2024-02-29                     NaN NaN   NaN  37616.199219
2024-03-01                     NaN NaN   NaN  37823.699219
2024-03-04                     NaN NaN   NaN  37634.250000
2024-03-05                     NaN NaN   NaN  37180.050781

Price      ^CNXIT - NIFTY IT._high                          \
Ticker                           - IT. NIFTY        ^CNXIT
Date
2018-01-02                     NaN NaN   NaN  11655.500000
2018-01-03                     NaN NaN   NaN  11693.349609
2018-01-04                     NaN NaN   NaN  11607.750000
2018-01-05                     NaN NaN   NaN  11691.450195
2018-01-08                     NaN NaN   NaN  11793.849609
...                            ...  ..   ...           ...
2024-02-28                     NaN NaN   NaN  38138.351562
2024-02-29                     NaN NaN   NaN  37896.050781
2024-03-01                     NaN NaN   NaN  37888.851562
2024-03-04                     NaN NaN   NaN  37733.250000
2024-03-05                     NaN NaN   NaN  37202.300781

Price      ^CNXIT - NIFTY IT._low                          \
Ticker                          - IT. NIFTY        ^CNXIT
Date
2018-01-02                    NaN NaN   NaN  11558.450195
2018-01-03                    NaN NaN   NaN  11573.250000
2018-01-04                    NaN NaN   NaN  11510.400391
2018-01-05                    NaN NaN   NaN  11541.799805
2018-01-08                    NaN NaN   NaN  11661.500000
...                           ...  ..   ...           ...
2024-02-28                    NaN NaN   NaN  37594.500000
2024-02-29                    NaN NaN   NaN  37414.949219
2024-03-01                    NaN NaN   NaN  37462.851562
2024-03-04                    NaN NaN   NaN  37279.449219
2024-03-05                    NaN NaN   NaN  36613.101562

Price      ^CNXIT - NIFTY IT._close                          \
Ticker                            - IT. NIFTY        ^CNXIT
Date
2018-01-02                      NaN NaN   NaN  11602.349609
2018-01-03                      NaN NaN   NaN  11586.700195
2018-01-04                      NaN NaN   NaN  11590.799805
2018-01-05                      NaN NaN   NaN  11633.549805
2018-01-08                      NaN NaN   NaN  11776.849609
...                             ...  ..   ...           ...
2024-02-28                      NaN NaN   NaN  37741.750000
2024-02-29                      NaN NaN   NaN  37720.398438
2024-03-01                      NaN NaN   NaN  37516.050781
2024-03-04                      NaN NaN   NaN  37314.800781
2024-03-05                      NaN NaN   NaN  36720.750000

Price      ^CNXIT - NIFTY IT._volume
Ticker                             - IT. NIFTY ^CNXIT
Date
2018-01-02                       NaN NaN   NaN      0
2018-01-03                       NaN NaN   NaN      0
2018-01-04                       NaN NaN   NaN      0
2018-01-05                       NaN NaN   NaN      0
2018-01-08                       NaN NaN   NaN      0
...                              ...  ..   ...    ...
2024-02-28                       NaN NaN   NaN  14800
2024-02-29                       NaN NaN   NaN  26400
2024-03-01                       NaN NaN   NaN  18800
2024-03-04                       NaN NaN   NaN  14500
2024-03-05                       NaN NaN   NaN  18100

[1516 rows x 20 columns]

In [11]:
import yfinance as yf
import datetime
import pandas as pd

# Define symbols, start, and end dates
symbols = ['^DJI', 'BTC-USD', 'ETH-USD', 'CL=F', 'GC=F', 'SI=F', 'NG=F', 'DX-Y.NYB', '^BSESN', '^NDX', '^GSPC', '^NSEI']
start = datetime.datetime(2018, 1, 1)
end = datetime.datetime(2024, 3, 6)

# Function to fetch historical data for a symbol
def fetch_data(symbol):
    data = yf.download(symbol, start=start, end=end)
    return data[['Open','High','Low' ,'Close', 'Volume']].rename(columns={'Open': f'{symbol}_open','Low': f'{symbol}_low','High': f'{symbol}_high','Close': f'{symbol}_close', 'Volume': f'{symbol}_volume'})

# Fetch data for all symbols and create a DataFrame
dfs = [fetch_data(symbol) for symbol in symbols]
result_df = pd.concat(dfs, axis=1, join='inner')

# Print the resulting DataFrame
print(result_df.head())

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

               ^DJI_open     ^DJI_high      ^DJI_low    ^DJI_close  \
Date
2018-01-02  24809.349609  24864.189453  24741.699219  24824.009766
2018-01-03  24850.449219  24941.919922  24825.550781  24922.679688
2018-01-04  24964.859375  25105.960938  24963.269531  25075.130859
2018-01-05  25114.919922  25299.789062  25112.009766  25295.869141
2018-01-08  25308.400391  25311.990234  25235.410156  25283.000000

            ^DJI_volume  BTC-USD_open  BTC-USD_high   BTC-USD_low  \
Date
2018-01-02    341130000  13625.000000  15444.599609  13163.599609
2018-01-03    456790000  14978.200195  15572.799805  14844.500000
2018-01-04    403280000  15270.700195  15739.700195  14522.200195
2018-01-05    358020000  15477.200195  17705.199219  15202.799805
2018-01-08    341390000  16476.199219  16537.900391  14208.200195

            BTC-USD_close  BTC-USD_volume  ...   ^GSPC_open   ^GSPC_high  \
Date                                       ...
2018-01-02   14982.099609     16846600192  ...  2683.729980  2695.889893
2018-01-03   15201.000000     16871900160  ...  2697.850098  2714.370117
2018-01-04   15599.200195     21783199744  ...  2719.310059  2729.290039
2018-01-05   17429.500000     23840899072  ...  2731.330078  2743.449951
2018-01-08   15170.099609     18413899776  ...  2742.669922  2748.510010

              ^GSPC_low  ^GSPC_close  ^GSPC_volume    ^NSEI_open  \
Date
2018-01-02  2682.360107  2695.810059    3397430000  10477.549805
2018-01-03  2697.770020  2713.060059    3544030000  10482.650391
2018-01-04  2719.070068  2723.989990    3697340000  10469.400391
2018-01-05  2727.919922  2743.149902    3239280000  10534.250000
2018-01-08  2737.600098  2747.709961    3246160000  10591.700195

              ^NSEI_high     ^NSEI_low   ^NSEI_close  ^NSEI_volume
Date
2018-01-02  10495.200195  10404.650391  10442.200195        153400
2018-01-03  10503.599609  10429.549805  10443.200195        167300
2018-01-04  10513.000000  10441.450195  10504.799805        174900
2018-01-05  10566.099609  10520.099609  10558.849609        180900
2018-01-08  10631.200195  10588.549805  10623.599609        169000

[5 rows x 60 columns]

In [12]:
result_df

,^DJI_open,^DJI_high,^DJI_low,^DJI_close,^DJI_volume,BTC-USD_open,BTC-USD_high,BTC-USD_low,BTC-USD_close,BTC-USD_volume,...,^GSPC_open,^GSPC_high,^GSPC_low,^GSPC_close,^GSPC_volume,^NSEI_open,^NSEI_high,^NSEI_low,^NSEI_close,^NSEI_volume
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,24809.349609,24864.189453,24741.699219,24824.009766,341130000,13625.000000,15444.599609,13163.599609,14982.099609,16846600192,...,2683.729980,2695.889893,2682.360107,2695.810059,3397430000,10477.549805,10495.200195,10404.650391,10442.200195,153400
2018-01-03,24850.449219,24941.919922,24825.550781,24922.679688,456790000,14978.200195,15572.799805,14844.500000,15201.000000,16871900160,...,2697.850098,2714.370117,2697.770020,2713.060059,3544030000,10482.650391,10503.599609,10429.549805,10443.200195,167300
2018-01-04,24964.859375,25105.960938,24963.269531,25075.130859,403280000,15270.700195,15739.700195,14522.200195,15599.200195,21783199744,...,2719.310059,2729.290039,2719.070068,2723.989990,3697340000,10469.400391,10513.000000,10441.450195,10504.799805,174900
2018-01-05,25114.919922,25299.789062,25112.009766,25295.869141,358020000,15477.200195,17705.199219,15202.799805,17429.500000,23840899072,...,2731.330078,2743.449951,2727.919922,2743.149902,3239280000,10534.250000,10566.099609,10520.099609,10558.849609,180900
2018-01-08,25308.400391,25311.990234,25235.410156,25283.000000,341390000,16476.199219,16537.900391,14208.200195,15170.099609,18413899776,...,2742.669922,2748.510010,2737.600098,2747.709961,3246160000,10591.700195,10631.200195,10588.549805,10623.599609,169000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-28,38938.078125,38956.460938,38741.679688,38949.019531,272560000,57071.097656,63913.132812,56738.425781,62504.789062,83239156760,...,5067.200195,5077.370117,5058.350098,5069.759766,3789370000,22214.099609,22229.150391,21915.849609,21951.150391,203000
2024-02-29,39013.750000,39074.128906,38809.281250,38996.390625,519690000,62499.183594,63585.644531,60498.730469,61198.382812,65496611844,...,5085.359863,5104.990234,5061.890137,5096.270020,5219740000,21935.199219,22060.550781,21860.650391,21982.800781,360200
2024-03-01,38989.511719,39120.359375,38850.500000,39087.378906,331030000,61168.062500,63155.101562,60802.527344,62440.632812,40186368423,...,5098.509766,5140.330078,5094.160156,5137.080078,4748110000,22048.300781,22353.300781,22047.750000,22338.750000,351500
2024-03-04,38968.769531,39087.859375,38913.300781,38989.828125,386290000,63137.003906,68537.031250,62386.519531,68330.414062,70670471105,...,5130.990234,5149.669922,5127.180176,5130.950195,4758440000,22403.500000,22440.900391,22358.300781,22405.599609,298800
2024-03-05,38906.980469,38906.980469,38457.828125,38585.191406,393750000,68341.054688,69170.625000,59323.910156,63801.199219,102802940877,...,5110.520020,5114.540039,5056.819824,5078.649902,4418410000,22371.250000,22416.900391,22269.150391,22356.300781,296200

In [13]:
result_df.to_csv("global_indices.csv")